Ewb 1226 Add ability to connect to aes server without user authentication
zepben/eas-client-python pull request #3
Opened 2022-02-08 04:47 UTC by Lax125

2022-02-08 04:47 UTC, ryanjcoleman commented
Task linked: [EWB-1226 Fix no auth support in eas-python-client](https://app.clickup.com/t/6929263/EWB-1226)

2022-02-10 02:35 UTC, Lax125 commented
- [ ] Accept https://github.com/zepben/zepben-auth-python/pull/5 for checks to pass

2022-02-15 07:59 UTC, kgreav requested changes
This needs a changelog update indicating the breaking changes (style classes and token fetcher stuff).
Also can you have a look into creating tests for the EasClient? Maybe just some basic init tests + a test for the certificate stuff would be a good start (you like security right? :wink: )

2022-02-21 06:13 UTC, kgreav approved these changes

2022-02-21 06:14 UTC, merged