EWB-1744: Raise error when attempting to configure auth on EasClient for HTTP server
zepben/eas-client-python pull request #8
Opened 2022-07-20 06:20 UTC by Lax125

Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

2022-07-20 06:20 UTC, ryanjcoleman commented
Task linked: [EWB-1744 Raise error in EasClient if initialised with auth but non https protocol](https://app.clickup.com/t/6929263/EWB-1744)

2022-07-20 10:57 UTC, kgreav requested changes

2022-07-20 10:57 UTC, kgreav commented on src/zepben/eas/client/eas_client.py
> +            - Specifying the client ID of the Auth0 via the client_id parameter, plus one of the following:
nit: `of the Auth0 application`

2022-07-20 10:57 UTC, kgreav commented on src/zepben/eas/client/eas_client.py
> +              If this method id used, the auth configuration will be fetched from the Evolve App Server at the path
nit: `if this method is used`

2022-07-20 10:57 UTC, kgreav commented on src/zepben/eas/client/eas_client.py
> +        :param host: The domain of the Evolve App Server, including the protocol, e.g. "evolve.local"
this doesn't include the protocol.

2022-07-20 10:57 UTC, kgreav commented on src/zepben/eas/client/eas_client.py
> +            - Specifying the client ID of the Auth0 via the client_id parameter, plus one of the following:
Can you also re-order these? We prefer people use the client id + username/password or secret over the zepben token fetcher, so better to make the first thing in the list the one most relevant to users.

2022-07-20 10:57 UTC, kgreav commented on src/zepben/eas/client/eas_client.py
> +        :param token_fetcher: A ZepbenTokenFetcher used to fetch auth tokens for access to the Evolve App Server.
Also here move this to below all the username/password options as its not preferred

2022-07-20 10:57 UTC, kgreav commented on tox.ini
> +    bash -ec 'if [[ -n $COVERALLS_REPO_TOKEN ]]; then coveralls; fi'
we don't need coveralls anymore, we're using codecov, which you should be able to change to look like the [evolve-sdk-python tox.ini](https://github.com/zepben/evolve-sdk-python/blob/main/tox.ini)

2022-07-22 05:23 UTC, kgreav commented
Looks good, I just added some extra checks to force the user into picking one set of creds so that we don't have ambiguous behaviour if you mistakenly send both (e.g token fetcher and username+password).

2022-07-22 05:23 UTC, kgreav approved these changes

2022-07-22 05:26 UTC, merged